import { ICategory, IProduct, IBanner } from '@/types';

export const SAMPLE_CATEGORIES: ICategory[] = [
  {
    _id: 'cat_road',
    name: 'Road Bikes',
    slug: 'road-bikes',
    description: 'Aerodynamic speed machines with ultra-light carbon frames.',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80',
    isActive: true,
    order: 1,
    productCount: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_mtb',
    name: 'Mountain Bikes',
    slug: 'mountain-bikes',
    description: 'Heavy-duty suspension and hydraulic disc brakes for rugged trails.',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
    isActive: true,
    order: 2,
    productCount: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_ladies',
    name: 'Ladies Cycle',
    slug: 'ladies-bicycles',
    description: 'Ergonomic step-through frames, comfortable posture, and stylish city basket designs.',
    image: '/images/categories/ladies-bicycles.jpg',
    isActive: true,
    order: 3,
    productCount: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_disc_brake',
    name: 'Disc Brake Cycles',
    slug: 'disc-brake-cycles',
    description: 'Precision mechanical & hydraulic disc braking systems for all-weather stopping power.',
    image: '/images/categories/disc-brake-cycles.jpg',
    isActive: true,
    order: 4,
    productCount: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_standard',
    name: 'Standard Cycles',
    slug: 'standard-cycles',
    description: 'Heavy-duty classic single-speed & multi-speed utility cycles built for lifetime durability.',
    image: '/images/categories/standard-cycles.jpg',
    isActive: true,
    order: 5,
    productCount: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_junior',
    name: 'Junior Bikes',
    slug: 'junior-bikes',
    description: 'Lightweight, ergonomic 20" to 24" bicycles designed for growing youths.',
    image: 'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=800&q=80',
    isActive: true,
    order: 6,
    productCount: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_kids',
    name: 'Kids Cycle',
    slug: 'kids-bikes',
    description: 'Safe, durable starter cycles with training wheels for young children.',
    image: 'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=800&q=80',
    isActive: true,
    order: 7,
    productCount: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'cat_gear',
    name: 'All Spare Items Available',
    slug: 'cycling-accessories',
    description: '100% genuine auto spare parts, cycling helmets, lights, and tools.',
    image: 'https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=800&q=80',
    isActive: true,
    order: 8,
    productCount: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const SAMPLE_PRODUCTS: IProduct[] = [
  {
    _id: 'prod_1',
    name: 'Srirama Apex Carbon Aero Road Bike',
    slug: 'srirama-apex-carbon-aero-road-bike',
    brand: 'Srirama Pro',
    category: 'cat_road',
    categorySlug: 'road-bikes',
    categoryName: 'Road Bikes',
    price: 68999,
    salePrice: 58999,
    stock: 12,
    sku: 'SRC-RD-001',
    images: [
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=1000&q=80',
      'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=1000&q=80',
    ],
    shortDescription:
      'Toray T800 full carbon monocoque aero frame, Shimano 105 R7000 22-Speed drivetrain.',
    description:
      'Engineered for sheer velocity and endurance. Equipped with Shimano 105 dual control shifters, aerodynamic carbon wheelset, and responsive dual pivot calliper brakes for blistering speeds on open highways.',
    specifications: [
      { key: 'Frame', value: 'Toray T800 High Modulus Carbon Fiber Aero' },
      { key: 'Fork', value: 'Full Carbon with Tapered Steerer' },
      { key: 'Drivetrain', value: 'Shimano 105 R7000 2x11 Speed' },
      { key: 'Brakes', value: 'Shimano 105 Dual-Pivot Callipers' },
      { key: 'Tires', value: 'Continental Ultra Sport III 700x25C' },
      { key: 'Weight', value: '8.4 kg' },
    ],
    variants: [
      { size: '52 cm (S)', stock: 4 },
      { size: '54 cm (M)', stock: 5 },
      { size: '56 cm (L)', stock: 3 },
    ],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    ratings: 4.9,
    numReviews: 42,
    tags: ['road bike', 'carbon', 'shimano 105', 'aero'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_2',
    name: 'Srirama Terra Pro 29" Full Suspension MTB',
    slug: 'srirama-terra-pro-29-full-suspension-mtb',
    brand: 'Srirama Trail',
    category: 'cat_mtb',
    categorySlug: 'mountain-bikes',
    categoryName: 'Mountain Bikes',
    price: 54999,
    salePrice: 47999,
    stock: 8,
    sku: 'SRC-MTB-002',
    images: [
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1000&q=80',
      'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=1000&q=80',
    ],
    shortDescription:
      'Hydroformed 6061-T6 alloy frame with RockShox 120mm air lockout suspension and Shimano Deore 1x12 speed.',
    description:
      'Tackle rough descents and steep switchbacks effortlessly. Features progressive trail geometry, Shimano hydraulic disc brakes with 180mm rotors for immense stopping power, and Maxxis Ardent high-traction knobby tires.',
    specifications: [
      { key: 'Frame', value: 'Hydroformed 6061 Double-Butted Aluminum' },
      { key: 'Front Fork', value: 'Air Suspension 120mm Travel with Lockout' },
      { key: 'Gears', value: 'Shimano Deore M6100 1x12 Speed' },
      { key: 'Brakes', value: 'Shimano MT200 Hydraulic Disc' },
      { key: 'Tires', value: 'Maxxis Ardent 29x2.25' },
      { key: 'Weight', value: '13.2 kg' },
    ],
    variants: [
      { size: 'Medium (17")', stock: 4 },
      { size: 'Large (19")', stock: 4 },
    ],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    ratings: 4.8,
    numReviews: 29,
    tags: ['mtb', 'mountain bike', 'suspension', 'hydraulic'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_3',
    name: 'Srirama Elegance 26" Ladies City Comfort Bicycle',
    slug: 'srirama-elegance-26-ladies-city-comfort-bicycle',
    brand: 'Srirama Ladies',
    category: 'cat_ladies',
    categorySlug: 'ladies-bicycles',
    categoryName: 'Ladies Bicycles',
    price: 18999,
    salePrice: 14999,
    stock: 15,
    sku: 'SRC-LD-003',
    images: [
      'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=1000&q=80',
      'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=1000&q=80',
    ],
    shortDescription:
      'Low step-through alloy frame, cushioned spring saddle, front wicker basket, and Shimano 7-speed gearing.',
    description:
      'Designed specifically for women riders seeking comfort, elegance, and effortless city commuting. Features upright handlebars and dress guard.',
    specifications: [
      { key: 'Frame', value: 'Step-Through Aluminum Alloy 6061' },
      { key: 'Gears', value: 'Shimano Tourney 7-Speed' },
      { key: 'Basket', value: 'Front Mounted Heavy-Duty Basket Included' },
      { key: 'Brakes', value: 'Power Alloy V-Brakes' },
    ],
    variants: [{ size: '26" Wheel (Standard)', stock: 15 }],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    ratings: 4.9,
    numReviews: 28,
    tags: ['ladies', 'women', 'basket', 'comfort'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_4',
    name: 'Srirama Phantom Pro 27.5" Dual Disc Brake Cycle',
    slug: 'srirama-phantom-pro-275-dual-disc-brake-cycle',
    brand: 'Srirama Pro',
    category: 'cat_disc_brake',
    categorySlug: 'disc-brake-cycles',
    categoryName: 'Disc Brake Cycles',
    price: 26999,
    salePrice: 21999,
    stock: 20,
    sku: 'SRC-DB-004',
    images: [
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=1000&q=80',
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=1000&q=80',
    ],
    shortDescription:
      'Precision dual hydraulic disc brakes (160mm rotors), 21-speed EZ-Fire shifters, and zoom front suspension fork.',
    description:
      'Built for maximum stopping safety on wet or dry roads. Features high-tensile alloy frame and double-wall alloy rims.',
    specifications: [
      { key: 'Frame', value: 'Lightweight 6061 Double-Butted Alloy' },
      { key: 'Brakes', value: 'Logan Hydraulic Dual Disc (160mm Rotors)' },
      { key: 'Shifters', value: 'Shimano EF500 21-Speed' },
      { key: 'Fork', value: 'Zoom 100mm Suspension with Lockout' },
    ],
    variants: [
      { size: '18" Frame', stock: 12 },
      { size: '20" Frame', stock: 8 },
    ],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    ratings: 4.8,
    numReviews: 39,
    tags: ['disc brake', 'hydraulic', '21 speed', 'safety'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_5',
    name: 'Srirama Blaze Junior 20" Kids MTB',
    slug: 'srirama-blaze-junior-20-kids-mtb',
    brand: 'Srirama Junior',
    category: 'cat_kids',
    categorySlug: 'kids-bikes',
    categoryName: 'Kids & Junior Bikes',
    price: 13999,
    salePrice: 10999,
    stock: 14,
    sku: 'SRC-KD-005',
    images: ['https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=1000&q=80'],
    shortDescription:
      'Durable hi-tensile steel frame with front suspension, Shimano 6-speed revoshift, and easy-reach child brake levers.',
    description:
      'The perfect ride for adventurous kids aged 6 to 10 years. Features low standover height, vibrant paint, and safety chain guard.',
    specifications: [
      { key: 'Frame', value: 'Hi-Tensile Steel with Low Standover' },
      { key: 'Suspension', value: 'Coil Spring 50mm Travel' },
      { key: 'Gears', value: 'Shimano Revoshift 6-Speed' },
    ],
    variants: [{ size: '20" Wheel (Ages 6-10)', stock: 14 }],
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    ratings: 4.8,
    numReviews: 12,
    tags: ['kids', 'junior', '20 inch'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_6',
    name: 'Srirama AeroShield Pro Cycling Helmet',
    slug: 'srirama-aeroshield-pro-cycling-helmet',
    brand: 'Srirama Gear',
    category: 'cat_gear',
    categorySlug: 'cycling-accessories',
    categoryName: 'Cycling Accessories & Gear',
    price: 3499,
    salePrice: 2499,
    stock: 45,
    sku: 'SRC-ACC-006',
    images: ['https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=1000&q=80'],
    shortDescription:
      'In-mold EPS foam with polycarbonate shell, magnetic detachable eye visor, 22 air vents, and rear safety LED.',
    description:
      'Maximum safety meets aerodynamic airflow. CE & CPSC certified protection with dial-fit adjustment system.',
    specifications: [
      { key: 'Material', value: 'High-Density EPS + Polycarbonate In-Mold' },
      { key: 'Ventilation', value: '22 Aerodynamic Wind Tunnel Vents' },
      { key: 'Weight', value: '260 grams' },
    ],
    variants: [{ size: 'Medium / Large (56-62cm)', stock: 45 }],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    ratings: 4.9,
    numReviews: 64,
    tags: ['helmet', 'safety', 'gear'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_7',
    name: 'Srirama High-Lumen 1200LM Waterproof Bike Headlight Set',
    slug: 'srirama-high-lumen-1200lm-waterproof-bike-headlight-set',
    brand: 'Srirama Gear',
    category: 'cat_gear',
    categorySlug: 'cycling-accessories',
    categoryName: 'Cycling Accessories & Gear',
    price: 2199,
    salePrice: 1599,
    stock: 30,
    sku: 'SRC-ACC-007',
    images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=1000&q=80'],
    shortDescription:
      'Aircraft grade aluminum 1200 lumens dual LED front light + smart auto brake sensing tail light.',
    description:
      'Illuminate your night rides with total confidence. IPX6 waterproof rating, 5 lighting modes, fast USB-C rechargeable port.',
    specifications: [
      { key: 'Brightness', value: '1200 Lumens Max' },
      { key: 'Battery', value: '4000mAh Lithium Rechargeable' },
    ],
    variants: [{ size: 'Universal Mount', stock: 30 }],
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    ratings: 4.8,
    numReviews: 53,
    tags: ['lights', 'led', 'night ride'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'prod_8',
    name: 'Srirama Heavy-Duty Classic 28" Standard Roadster Cycle',
    slug: 'srirama-heavy-duty-classic-28-standard-roadster-cycle',
    brand: 'Srirama Classic',
    category: 'cat_standard',
    categorySlug: 'standard-cycles',
    categoryName: 'Standard Cycles',
    price: 9999,
    salePrice: 7999,
    stock: 25,
    sku: 'SRC-STD-008',
    images: ['https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=1000&q=80'],
    shortDescription:
      'Heavy-gauge tubular steel frame, full chain cover, heavy rear carrier, and traditional rod brakes.',
    description:
      'The legendary Indian roadster built for utility and ultimate durability. Engineered with reinforced steel, wide leather sprung saddle, and heavy luggage carrier.',
    specifications: [
      { key: 'Frame', value: 'Heavy Duty Reinforced Tubular Steel' },
      { key: 'Brakes', value: 'Traditional Steel Rod Brakes' },
      { key: 'Rims', value: '28 x 1-1/2 Heavy Duty Steel Rims' },
      { key: 'Carrier', value: 'Integrated Heavy-Duty Luggage Carrier' },
    ],
    variants: [{ size: '28" Frame (Standard)', stock: 25 }],
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    ratings: 4.9,
    numReviews: 87,
    tags: ['standard', 'roadster', 'utility', 'heavy duty'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
